### ISSUE TITLE
manage a poll: User Story 1

### ISSUE THREAD

**Issue by BrianStritch** [BrianStritch/My_first_agile_project#8]
In order to **collect user feedback** as an **administrator**, I can **get the username and location in the form details**

## Acceptance Criteria:
 - Input field for username in poll form details
 - Input field for users location in poll form

## Tasks:
- [ ] input field for username
- [ ] input field for users location
- [ ] input fields set as required
